#!/usr/bin/env sh

#ddev-generated
## Description: Run valkey-cli inside the Valkey container
## Usage: redis-cli [flags] [args]
## Example: "ddev redis-cli KEYS *" or "ddev redis-cli INFO" or "ddev redis-cli --version"
## Aliases: redis

if [ -f /etc/redis/conf/security.conf ]; then
  valkey-cli -p 6379 -h "${REDIS_HOSTNAME:-redis}" -a redis --no-auth-warning $@
else
  valkey-cli -p 6379 -h "${REDIS_HOSTNAME:-redis}" $@
fi
